import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import MovieList from '@/components/movieList'
import MovieListHeading from '@/components/movieListHeading'
import SearchBox from '@/components/searchBox'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [movies, setMovies] = useState([]);
  const [searchValue, setSearchValue] = useState("");


  const getMovieRequest = async (searchValue) => {

    const url = `https://www.omdbapi.com/?s='${searchValue}'&apikey=515d6411`;
    const response = await fetch(url);
    const responseJson = await response.json();
    if (responseJson.Search) {
      setMovies(responseJson.Search);
    }

  }

  useEffect(() => {
    getMovieRequest(searchValue);
  }, [searchValue]);
  //  getMovieRequest()
  return (
    <>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className='container-fluid movie-app'>
          <div className='row d-flex align-items-center mt-4 mb-4'>
            <MovieListHeading heading="movies" />
            <SearchBox searchValue={searchValue} setSearchValue={setSearchValue} />
          </div>
          <div className='row'>
            <MovieList movies={movies} />
          </div>
        </div>

      </main>
    </>
  )
}
